   hide circle
   skinparam linetype ortho

   entity "attributes" as attributes{
     --
     *ID : KEYTYPE
     entity : VARCHAR(50)
     groupID : INT
     title : VARCHAR(100)
     title_ru : VARCHAR(100)
     description : TEXT
     description_ru : TEXT
     comment : TEXT
     type : INT
     dictionary : VARCHAR(100)
     storage : ENUM('json','query')
     level : ENUM('CNV','SNV','transcript')
     editable : ENUM('no','yes')
     displayIfEmpty : ENUM('no','yes')
     displayOrder : INT
     urlMask : VARCHAR(100)
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "attribute_types" as attribute_types{
     --
     *ID : KEYTYPE
     title : VARCHAR(20)
     description : TEXT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "attribute_groups" as attribute_groups{
     --
     *ID : KEYTYPE
     title : VARCHAR(100)
     title_ru : VARCHAR(100)
     description : TEXT
     description_ru : TEXT
     comment : TEXT
     displayOrder : INT
     viewName : VARCHAR(100)
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "attribute_resources" as attribute_resources{
     --
     *ID : KEYTYPE
     attribute : INT
     resource : INT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "pathogenicity" as pathogenicity{
     --
     *ID : KEYTYPE
     title : VARCHAR(20)
     description : TEXT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "pathogenicity_authority" as pathogenicity_authority{
     --
     *ID : KEYTYPE
     title : VARCHAR(20)
     description : TEXT
     resource : INT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "resources" as resources{
     --
     *ID : KEYTYPE
     type : ENUM('database','format','other','program','recommendation')
     title : VARCHAR(100)
     version : VARCHAR(50)
     description : TEXT
     url : VARCHAR(100)
     license : VARCHAR(200)
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "resource_recommendations" as resource_recommendations{
     --
     *ID : KEYTYPE
     resource : INT
     recommendation : INT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "rule_sets" as rule_sets{
     --
     *ID : KEYTYPE
     title : VARCHAR(100)
     version : VARCHAR(50)
     description : TEXT
     recommendation : INT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "rules" as rules{
     --
     *ID : KEYTYPE
     attribute : INT
     code : TEXT
     desription : TEXT
     comment : TEXT
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "snv_" as snv_{
     --
     *ID : KEYTYPE
     vcf_chrom : VARCHAR(50)
     vcf_pos : INT
     vcf_id : VARCHAR(200)
     vcf_ref : VARCHAR(50)
     vcf_alt : VARCHAR(50)
     vcf_qual : DECIMAL(4,1)
     vcf_filter : VARCHAR(50)
     vcf_info : TEXT
     vcf_format : VARCHAR(1000)
     attributes : JSON
     pathogenicity : INT
     pathogenicityAuthority : INT
     isAttached : ENUM('no','yes')
     isHidden : ENUM('no','yes')
     includeInReport : ENUM('no','yes')
     reportComment : ENUM('no','yes')
    }

   entity "snv_features_" as snv_features_{
     --
     *ID : KEYTYPE
     snv : INT
     feature : VARCHAR(50)
     attributes : JSON
    }

   entity "snv_meta_" as snv_meta_{
     --
     section : VARCHAR(50)
     value : VARCHAR(10000)
     ID : VARCHAR(50)
     description : VARCHAR(200)
     type : ENUM('Character','Flag','Float','Integer','String')
     number : VARCHAR(2)
     url : VARCHAR(200)
    }

   entity "snv_history" as snv_history{
     --
     *ID : KEYTYPE
     VEP_ID : VARCHAR(50)
     location : VARCHAR(50)
     allele : VARCHAR(10)
     pathogenicity : INT
     pathogenicityAuthority : INT
     attributes : JSON
     creationDate___ : TIMESTAMP
     modificationDate___ : TIMESTAMP
     whoInserted___ : VARCHAR(100)
     whoModified___ : VARCHAR(100)
    }

   entity "snv_transcripts_history" as snv_transcripts_history{
     --
     *ID : KEYTYPE
     SNV : INT
     transcript : VARCHAR(50)
     attributes : JSON
    }

   attribute_resources }o..|| attributes
   attribute_resources }o..|| resources
   attributes }o..|| attribute_groups
   attributes }o..|| attribute_types
   pathogenicity_authority }o..|| resources
   resource_recommendations }o..|| resources
   resource_recommendations }o..|| resources
   rule_sets }o..|| resources
   rules }o..|| attributes
   snv_ }o..|| pathogenicity
   snv_ }o..|| pathogenicity_authority
   snv_features_ }o..|| snv_
   snv_history }o..|| pathogenicity
   snv_history }o..|| pathogenicity_authority
   snv_transcripts_history }o..|| snv_history
