diagrams:
  - attributes:
      tables: 
        - attributes
        - attribute_types
        - attribute_groups
        - attribute_resources
        - attribute_rules
        - pathogenicity
        - pathogenicity_authority
        - resources
        - resource_recommendations
        - snv_
        - snv_transcripts_
        - snv_history
        - snv_transcripts_history
  - projects:
      tables: [projects, runs, samples]
  - devices:
      tables: [devices, device_types, device_statuses]
  - nextflow:
      tables: [nf_workflows, nf_heartbeat]

nested_tables:
  - attributes 
  - attribute_types 
  - attribute_groups
  - attribute_resources 
  - resources
  - resource_recommendations
  - devices
  - device_types
  - device_statuses
  - projects
  - runs
  - samples
  - nf_workflows
  - nf_heartbeat

  