diagrams:
  - attributes:
      tables:
        - attributes
        - attribute_types
        - attribute_groups
        - attribute_resources
        - pathogenicity
        - pathogenicity_authority
        - resources
        - resource_recommendations
        - rules
        - rule_sets
        - rule_set_rules
        - snv_
        - snv_features_
        - snv_meta_
        - snv_history
        - snv_transcripts_history
  - projects:
      tables: 
        - projects
        - runs
        - run_samples
        - samples
        - sample_types
        - sample_templates
        - file_info
        - file_types
        - task_info
        - task_runs
        - workflow_info
        - workflow_runs
  - rules:
      tables: [attributes, rule_sets, rules, rule_set_rules]
  - devices:
      tables: [devices, device_types, device_statuses]
  - nextflow:
      tables: [nf_workflows, nf_heartbeat]

nested_tables:
  - attributes 
  - attribute_types 
  - attribute_groups
  - attribute_resources 
  - resources
  - resource_recommendations
  - devices
  - device_types
  - device_statuses
  - projects
  - runs
  - samples
  - nf_workflows
  - nf_heartbeat

  